### ISSUE TITLE
Split the app.rb in different files

### ISSUE THREAD

**Issue by Davidslv** [mjhea0/sinatra-blog#1]
Hi,
I know this is an example, and as an example - should be a good one.

Feel free to not follow what I'm going to say, it's my personal opinion.

I think you should:
- Create a folder for Post Model
- Another one for the helpers
- And a folder for your post controller
- And your endpoint /posts/create should be "/posts/new" which is exactly what you have inside.

Thanks for the example.
David

**Comment by mjhea0** [comment]
I agree with you. Let me try to get it down in the next few days. You can fork it in the meantime if you'd like and make the changes yourself, then merge back?
