### ISSUE TITLE
sqlite3 instead of sqlite

### ISSUE THREAD

**Issue by gerep** [mjhea0/sinatra-blog#2]
Here: https://github.com/mjhea0/sinatra-blog/blob/master/environments.rb#L2

Shouldn't it be _sqlite3_ instead of _sqlite_? I get errors when using _sqlite_ but with _sqlite3_ it works

```
set :database, 'sqlite3:///dev.db'
```

**Comment by mjhea0** [comment]
That's the URI, so it should be just sqlite. Strange. What are the errors?
